project:
  type: website
  output-dir: docs
  resources:
    - CNAME

website:
  title: "Tuhinur Rahman Chowdhury"
  navbar:
    background: "#1a2744"
    foreground: "white"
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - href: blog.qmd
        text: Blog
      - href: about.qmd
        text: About
    right:
      - href: cv.qmd
        text: CV

format:
  html:
    theme: [cosmo, custom.scss]
    toc: false
    code-fold: true
    code-tools: true

execute:
  freeze: auto